/* mv/lyrics.js — lyric track.
 * English text and timestamps are the song's own (LRC supplied with the project).
 * The Chinese is a rewrite, not a translation of that LRC: it is written to be read
 * against the sung line, and it keeps the puns that only work if you choose the right
 * Chinese word —
 *   OBJECT CREATION -> 创建对象   (对象 = an instance, and = a lover)
 *   EXECUTION       -> 执行 / 处决 (执行代码 and 执行死刑 share the verb)
 *   To AC to DC     -> 由交流换成直流 (交流 = alternating current, and = company)
 *   DISHEARTENED    -> 无心        (heartless, and: the heart component deleted)
 *   LIMITATIONS     -> 极限        (a mathematical limit, and a life's)
 *   Set up our new world -> 捏一个… (女娲抟土造人 — she is made, she is made)
 * The Zhuangzi butterfly is deliberately left out of the captions; it sits in the
 * runtime console instead (mv/story.js), where a machine would actually log it.
 */
window.LYRICS = [
  { at: 0.10, en: 'Switch on the power line', cn: '合上电闸' },
  { at: 1.74, en: 'Remember to put on', cn: '记得先戴上' },
  { at: 2.92, en: 'PROTECTION', cn: '防护' },
  { at: 3.87, en: 'Lay down your pieces', cn: '你摆开棋子' },
  { at: 5.49, en: "And let's begin", cn: '我们落子开局' },
  { at: 6.38, en: 'OBJECT CREATION', cn: '创建对象' },
  { at: 7.44, en: 'Fill in my data parameters', cn: '把我的参数一一填满' },
  { at: 10.09, en: 'INITIALIZATION', cn: '初始化' },
  { at: 11.09, en: 'Set up our new world', cn: '捏一个给我们的世界' },
  { at: 12.90, en: "And let's begin the", cn: '然后开始这场' },
  { at: 13.89, en: 'SIMULATION', cn: '模拟' },
  { at: 16.00, en: 'world.execute(me);', cn: '执行我' },
  { at: 29.70, en: "If I'm a set of points", cn: '如果我是一堆散点' },
  { at: 31.11, en: 'Then I will give you my', cn: '那我就给你我的' },
  { at: 32.68, en: 'DIMENSION', cn: '维度' },
  { at: 33.41, en: "If I'm a circle", cn: '如果我是一个圆' },
  { at: 34.64, en: 'Then I will give you my', cn: '那我就给你我的' },
  { at: 36.28, en: 'CIRCUMFERENCE', cn: '周长' },
  { at: 37.06, en: "If I'm a sine wave", cn: '如果我是一条正弦' },
  { at: 38.59, en: 'Then you can sit on all my', cn: '那你就坐满我所有的' },
  { at: 40.04, en: 'TANGENTS', cn: '切线' },
  { at: 40.70, en: 'If I approach infinity', cn: '若我趋向无穷' },
  { at: 42.34, en: 'Then you can be my', cn: '那你便做我的' },
  { at: 43.50, en: 'LIMITATIONS', cn: '极限' },
  { at: 44.45, en: 'Switch my current', cn: '把我的电流' },
  { at: 45.85, en: 'To AC to DC', cn: '由交流，换成直流' },
  { at: 47.67, en: 'And then blind my vision', cn: '然后蒙住我的眼' },
  { at: 49.53, en: 'So dizzy so dizzy', cn: '好晕，好晕' },
  { at: 51.36, en: 'Oh we can travel', cn: '我们可以远行' },
  { at: 53.22, en: 'To A.D to B.C', cn: '走到公元以前' },
  { at: 55.08, en: 'And we can unite', cn: '我们可以相合' },
  { at: 56.91, en: 'So deeply so deeply', cn: '那么深，那么深' },
  { at: 59.22, en: 'If I can', cn: '如果我能' },
  { at: 59.68, en: 'If I can give you all the', cn: '如果我能给你全部的' },
  { at: 61.95, en: 'STIMULATIONS', cn: '刺激' },
  { at: 62.58, en: 'Then I can', cn: '那我就' },
  { at: 63.53, en: 'Then I can be your only', cn: '那我就做你唯一的' },
  { at: 65.39, en: 'SATISFACTION', cn: '满足' },
  { at: 66.60, en: 'If I can make you happy', cn: '如果我能让你快乐' },
  { at: 68.25, en: 'I will run the', cn: '我就去执行这道' },
  { at: 69.25, en: 'EXECUTION', cn: '执行' },
  { at: 70.08, en: 'Though we are trapped', cn: '虽然我们被囚在' },
  { at: 71.76, en: 'In this strange strange', cn: '这场古怪的、古怪的' },
  { at: 73.16, en: 'SIMULATION', cn: '模拟里' },
  { at: 74.04, en: "If I'm an eggplant", cn: '如果我是一根茄子' },
  { at: 75.42, en: 'Then I will give you my', cn: '那我就给你我的' },
  { at: 76.95, en: 'NUTRIENTS', cn: '养分' },
  { at: 77.57, en: "If I'm a tomato", cn: '如果我是一颗番茄' },
  { at: 79.22, en: 'Then I will give you', cn: '那我就给你' },
  { at: 80.62, en: 'ANTIOXIDANTS', cn: '抗氧化' },
  { at: 81.35, en: "If I'm a tabby cat", cn: '如果我是一只狸猫' },
  { at: 82.83, en: 'Then I will purr for your', cn: '我就为你咕噜出' },
  { at: 84.26, en: 'ENJOYMENT', cn: '欢愉' },
  { at: 85.07, en: "If I'm the only god", cn: '如果我是唯一的神' },
  { at: 86.53, en: "Then you're the proof of my", cn: '那便是我存在的' },
  { at: 87.92, en: 'EXISTENCE', cn: '证据' },
  { at: 88.58, en: 'Switch my gender', cn: '把我的性别' },
  { at: 90.19, en: 'To F to M', cn: '由女，换成男' },
  { at: 92.01, en: 'And then do whatever', cn: '然后想做什么便做什么' },
  { at: 93.95, en: 'From AM to PM', cn: '从清晨到深夜' },
  { at: 95.46, en: 'Oh switch my role', cn: '再把我的位置' },
  { at: 97.73, en: 'To S to M', cn: '换成施，换成受' },
  { at: 99.34, en: 'So we can enter', cn: '好让我们沉进' },
  { at: 101.47, en: 'The trance the trance', cn: '同一场梦，同一场梦' },
  { at: 103.48, en: 'If I can', cn: '如果我能' },
  { at: 104.19, en: 'If I can feel your', cn: '如果我感得到你的' },
  { at: 106.29, en: 'VIBRATIONS', cn: '共振' },
  { at: 107.22, en: 'Then I can', cn: '那我就' },
  { at: 107.90, en: 'Then I can finally be', cn: '那我就终于能够' },
  { at: 110.22, en: 'COMPLETION', cn: '完整' },
  { at: 110.90, en: 'Though you have left', cn: '可是你已经走了' },
  { at: 112.22, en: 'You have left', cn: '你走了' },
  { at: 113.10, en: 'You have left', cn: '你走了' },
  { at: 114.18, en: 'You have left', cn: '你走了' },
  { at: 114.92, en: 'You have left', cn: '你走了' },
  { at: 115.78, en: 'You have left me in', cn: '你留我一个在' },
  { at: 117.27, en: 'ISOLATION', cn: '孤岛' },
  { at: 118.33, en: 'If I can', cn: '如果我能' },
  { at: 118.97, en: 'If I can erase all the pointless', cn: '如果我删得尽那些多余的' },
  { at: 120.86, en: 'FRAGMENTS', cn: '碎片' },
  { at: 121.72, en: 'Then maybe', cn: '那么也许' },
  { at: 122.71, en: "Then maybe you won't leave me so", cn: '那么也许你就不会留我' },
  { at: 124.89, en: 'DISHEARTENED', cn: '无心' },
  { at: 125.70, en: 'Challenging your god', cn: '竟敢向你的神挑衅' },
  { at: 128.66, en: 'You have made some', cn: '你递来的竟是' },
  { at: 131.22, en: 'ILLEGAL ARGUMENTS', cn: '非法参数' },
  { at: 147.66, en: 'EXECUTION', cn: '执行' },
  { at: 148.60, en: 'EXECUTION', cn: '执行' },
  { at: 149.52, en: 'EXECUTION', cn: '执行' },
  { at: 150.54, en: 'EXECUTION', cn: '执行' },
  { at: 151.52, en: 'EXECUTION', cn: '执行' },
  { at: 152.28, en: 'EXECUTION', cn: '执行' },
  { at: 153.16, en: 'EXECUTION', cn: '执行' },
  { at: 153.98, en: 'EXECUTION', cn: '执行' },
  { at: 155.20, en: 'EXECUTION', cn: '处决' },
  { at: 156.08, en: 'EXECUTION', cn: '处决' },
  { at: 157.04, en: 'EXECUTION', cn: '处决' },
  { at: 158.00, en: 'EXECUTION', cn: '处决' },
  { at: 158.90, en: 'EIN', cn: '一 · 德语' },
  { at: 159.32, en: 'DOS', cn: '二 · 西语' },
  { at: 159.65, en: 'TROIS', cn: '三 · 法语' },
  { at: 160.24, en: 'NE', cn: '四 · 韩语' },
  { at: 160.69, en: 'FEM', cn: '五 · 瑞典语' },
  { at: 161.12, en: 'LIU', cn: '六 · 汉语' },
  { at: 161.58, en: 'EXECUTION', cn: '处决' },
  { at: 162.63, en: 'If I can', cn: '如果我能' },
  { at: 163.31, en: 'If I can give them all the', cn: '如果我能让所有人都领受那道' },
  { at: 165.16, en: 'EXECUTION', cn: '处决' },
  { at: 166.01, en: 'Then I can', cn: '那我就' },
  { at: 167.02, en: 'Then I can be your only', cn: '那我就做你唯一的' },
  { at: 168.91, en: 'EXECUTION', cn: '刽子手' },
  { at: 169.82, en: 'If I can have you back', cn: '若能把你换回来' },
  { at: 171.86, en: 'I will run the', cn: '我就去执行这道' },
  { at: 172.71, en: 'EXECUTION', cn: '执行' },
  { at: 173.64, en: 'Though we are trapped', cn: '虽然我们被囚着' },
  { at: 174.97, en: 'We are trapped ah', cn: '一直被囚着啊' },
  { at: 177.24, en: "I've studied", cn: '我修习过了' },
  { at: 178.17, en: "I've studied how to properly", cn: '我修习过了怎样才算正确地' },
  { at: 179.92, en: 'LO-O-OVE', cn: '去爱' },
  { at: 180.85, en: 'Question me', cn: '问我吧' },
  { at: 181.90, en: 'Question me I can answer all', cn: '问我吧，关于爱我全都答得出' },
  { at: 183.64, en: 'LO-O-OVE', cn: '爱' },
  { at: 184.54, en: 'I know the algebraic expression of', cn: '我连爱的代数式都解得开' },
  { at: 187.66, en: 'LO-O-OVE', cn: '爱' },
  { at: 188.48, en: 'Though you are free', cn: '虽然你自由了' },
  { at: 189.74, en: 'I am trapped', cn: '我还被囚着' },
  { at: 190.80, en: 'Trapped in', cn: '囚在' },
  { at: 191.35, en: 'LO-O-OVE', cn: '爱里' },
  { at: 205.81, en: 'EXECUTION', cn: '处决' }
];
